name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: wyvox/action@v1
      - run: pnpm lint
      - run: pnpm test

